# Autogenerated by devscripts/update-version.py

__version__ = '2025.12.26'

RELEASE_GIT_HEAD = '4f9d14d1e505f369a914fdd03e026b4ec83ce966'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'pantelisbi/yt-dlp'

ORIGIN = 'pantelisbi/yt-dlp'

_pkg_version = '2025.12.26'
